// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using twoday_Internship_Task.Database;

#nullable disable

namespace twoday_Internship_Task.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("twoday_Internship_Task.Database.DatabaseModels.Animal", b =>
                {
                    b.Property<string>("Species")
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnclosureName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Food")
                        .HasColumnType("INTEGER");

                    b.HasKey("Species");

                    b.HasIndex("EnclosureName");

                    b.ToTable("Animals", (string)null);
                });

            modelBuilder.Entity("twoday_Internship_Task.Database.DatabaseModels.Enclosure", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Location")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("Enclosures", (string)null);
                });

            modelBuilder.Entity("twoday_Internship_Task.Database.DatabaseModels.EnclosureObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnclosureName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnclosureName");

                    b.ToTable("EnclosureObjects", (string)null);
                });

            modelBuilder.Entity("twoday_Internship_Task.Database.DatabaseModels.Animal", b =>
                {
                    b.HasOne("twoday_Internship_Task.Database.DatabaseModels.Enclosure", null)
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("twoday_Internship_Task.Database.DatabaseModels.EnclosureObject", b =>
                {
                    b.HasOne("twoday_Internship_Task.Database.DatabaseModels.Enclosure", null)
                        .WithMany("Objects")
                        .HasForeignKey("EnclosureName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("twoday_Internship_Task.Database.DatabaseModels.Enclosure", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("Objects");
                });
#pragma warning restore 612, 618
        }
    }
}
